[project]
name = "chromium_search_engine_export"
version = "0.1.0"
description = "Chrome Based Search Engine Export"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pytest>=8.3.4",
    "PySide6>=6.6.0",
]
